### ISSUE TITLE
Remove "Calculate Average Size" and change "Calculate Concentration (nM)" script in RNA work flow

### ISSUE THREAD

**Issue by linnealafleur** [Clinical-Genomics/cg_lims#122]
Lims Issue
---------------

**Work Flow:** RNA v2
**Protocol:** Library Validation QC (RNA)
**Step:** Aggregate QC (Library Validation) (RNA)

**Description:** 
In the current aggregation step, there is a script "2. Calculate Average Size (bp)" which will make an average from the UDF "Size (bp)" for all samples. This average size is then used when calculating the nM concentration with the script "3. Calculate Concentration (nM)".
We would like the script for the Average Size calculation to be removed from this step. 
And that the script "3. Calculate Concentration (nM)" is changed so it uses "Size (bp)" to calculate the nM concentration instead of the "Average Size (bp)".

**Comment by cesve** [comment]
This will be fixed in RNA v3.

**Comment by cesve** [comment]
In the new workflow this issue has been fixed.

New workflow: _**RNA v3**_

The script "2. Calculate Average Size (bp)" has been removed.
The script "3. Calculate Concentration (nM)" has been removed

The script "2. Calculate Concentration (nM)" has been added. This is not a new script. It's also used in steps shown below. The scripts uses the UDF "Size (bp)" instead of the UDF "Average Size (bp)" to calculate the nM concentration.
![Screenshot 2022-02-02 at 10 27 08](https://user-images.githubusercontent.com/37171914/152127364-6874d44a-c3b9-48c1-9c56-c38275e9df62.png)


**_Test of new script_**
The size adjusted concentration, UDF "Concentration (nM)" calculated by the script was compared to the calculations made in sheet 1470:7.

**Comment by annaengstrom** [comment]
@cesve If it is only a matter of rounding of numbers then it is fine! No more calculations will be used after in the RNA workflow.

**Comment by cesve** [comment]
Great!
