### ISSUE TITLE
1499 ready to be merged and used in Atlas

### ISSUE THREAD

**Issue by MariaSalli** [Clinical-Genomics/cg_lims#254]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Library validation qc wgs v3
**Protocol:** CG002 - qPCR QC (Library Validation)
**Step:** CG002 - qPCR QC (Library Validation)

**Description:** Description: qPCR procedure for NGS using Bravo has been merged and is ready to be used in Atlas. Lims workflows need to be updated. The method is used in workflows, listed above.

**Comment by RasmusBurge-CG** [comment]
Hi @MariaSalli! Can you verify that the document is named "qPCR procedure for NGS using Bravo" now on atlas?

**Comment by RasmusBurge-CG** [comment]
This issue is blocked, this is due to there being no position "EPP Log" in the file section in the step. A new button and a new EPP Log position were made on stage, which fixed the problem. However, unable to test if "Calculate Concentration And Assign QC" works, "could not read dilutionfile". I believe this is due to differences between production and stage. Request input from colleagues.

**Comment by RasmusBurge-CG** [comment]
After a lot of effort "qPCR procedure for NGS using Bravo" is now available in the qPCR step. Due to the issues we have had with this step, I think we should wait with the removal of the AM doc before we run the step in production for a week.

**Comment by RasmusBurge-CG** [comment]
Done!
