### ISSUE TITLE
Add Hamilton Normalisation in micro prep

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#346]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Microbial WGS v6
**Protocol:** Nextera Microbial WGS v4 , CG002 - Normalization of microbial samples for sequencing
**Step:**Normalization of microbial samples v2 , CG002 - Normalization of microbial samples for sequencing

**Description:** Describe issue here!!!
Since the BRAVO is usually occupied we would like to be able to also do the normalisation on Hamilton using the Normalisation and Pooling protocol.

- [x] Add UDF option for adding the plate barcode
- [x] Add the script that generates the .csv file for Hamilton

**Comment by idalindegaard** [comment]
**Testing on LIMS stage:**

In step _Reception control_, protocol _Pre Processing Microbial v1_: Added a udf called "Output Container Barcode", where I added a random name representing the barcode for the plate. See picture below.
<img width="790" alt="Screenshot 2023-02-21 at 13 40 00" src="https://user-images.githubusercontent.com/82438141/220353972-115292de-c89b-4ab9-9f93-bb3ca5db4897.png">

In step _Normalization of microbial samples v2_, protocol _Nextera Microbial WGS v4_: Added new udf "Hamilton Instrument" and new option (Hamilton Normalisation and Pooling) method. Aliquot volumes were calculated and a name for the new udf "Output Container Barcode" was added as seen below. A negative control was added, sample named "NTC-CG-11".
<img width="671" alt="Screenshot 2023-02-21 at 14 01 06" src="https://user-images.githubusercontent.com/82438141/220354781-82ff1486-f551-4c38-8db8-21c2d186c662.png">

Same step: The new script Hamilton Normalization Microbial" was run and failed, since the negative control (NTC-CG-11) does not have a registered barcode. See below.
<img width="671" alt="Screenshot 2023-02-21 at 14 01 29" src="https://user-images.githubusercontent.com/82438141/220355761-20f864be-99be-402f-a3c5-6c58e95153ec.png">

Below is the file that was generated through the script. It has all information except for the barcode for the negative control.
<img width="990" alt="Screenshot 2023-02-21 at 14 02 09" src="https://user-images.githubusercontent.com/82438141/220356037-51cfaf7a-dfb6-48d4-a1f3-0bcae62e2dcb.png">

**Doing a new test without the negative control:**

When running the script again it succeeds. 
<img width="676" alt="Screenshot 2023-02-21 at 14 07 00" src="https://user-images.githubusercontent.com/82438141/220356420-1aede7cf-55d3-486c-aafb-1c4292145bb7.png">
<img width="1168" alt="Screenshot 2023-02-21 at 14 07 13" src="https://user-images.githubusercontent.com/82438141/220356480-47484b56-9c07-457f-b47e-dcde95233d52.png">
<img width="669" alt="Screenshot 2023-02-21 at 14 07 35" src="https://user-images.githubusercontent.com/82438141/220356499-c65786f7-e9fa-4db5-ba2e-9f5b177c873b.png">
<img width="987" alt="Screenshot 2023-02-21 at 14 24 21" src="https://user-images.githubusercontent.com/82438141/220356759-ac40898f-50f8-4b48-bffd-a32fd6eca713.png">

All information in the file corresponds to the right concentrations and barcodes that were registered. Everything works as it should. Since we need the negative controls (that are just added water and the order that has been made for these does not have registered barcodes) we need to find a way to get them through LIMS and add them to the plate. A suggestion is to add them as usually in LIMS and remove them from the Hamilton normalisation file, and then add the water manually after the normalisation has been done.

**Comment by idalindegaard** [comment]
@FayKanellidou @annaengstrom Testing has been done in LIMS stage, it works as it should. Except the NC that doesn't have a registered barcode. I added a suggestion in the conclusion. Shall I update the LIMS production workflow now?

**Comment by idalindegaard** [comment]
@FayKanellidou I talked with AL and she said you could test the script on stage as well, and make the tests on Hamilton through stage before deploying the results in LIMS-production. I can show you how to access stage and do this when we have time

**Comment by annaengstrom** [comment]
Please add a description to https://github.com/Clinical-Genomics/Lab-projects/issues/548 and in this issue perhaps why LIMS is updated (typically part of implementation - after verification has been completed and signed off) before the verification has been completed.

**Comment by idalindegaard** [comment]
Production LIMS has been updated with the same changes, so that tests can be run in that environment. The normalisation step can be run just as before and since the method instructions have not yet been updated, users won't have problems running it according to verified and correct instructions. @FayKanellidou
