### ISSUE TITLE
Bug in index2 barcode mismatch calculation for NovaSeqX sample sheet

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg_lims#392]
Lims Issue
---------------

The calculation of hamming distance between two index2 sequences assumes the reverse complement of the sequence; however, for NovaSeqX, complement reversion is never done. 
In more detail, in the function `cg_lims/EPPs/files/sample_sheet/create_sample_sheet.py:calculate_index_hamming_distance`, the hamming distance between two index2 sequences is calculated using the last nucleotides (the tail) of the sequence when it should be done using the first nucleotides (the head) of the sequence, as it is done with index1. This may lead to incorrect calculations of barcode mismatch values for index2.

**Comment by Karl-Svard** [comment]
Completely forgot to reply to this issue, sorry Sebastian!

It's actually not a bug. Just bad / unclear coding 😅. Lets go through the mess that I wrote:

`calculate_index_hamming_distance` takes two `IlluminaIndex` objects as input. Chosen from the set of all registered i7 and i5 indexes loaded onto the flow cell. First it makes sure that the indexes are of the same type as they can only clash in that scenario:

```python
    if index_1.type != index_2.type:
        return None
``` 

Then we directly compare them if they are of the same length:

```python
    elif len(index_1.sequence) == len(index_2.sequence):
        return string_hamming_distance(index_1=index_1.sequence, index_2=index_2.sequence)
``` 

If index_2 is longer then we will go into:

```python
        if index_1.type == IndexType.INDEX_1:
            return string_hamming_distance(
                index_1=index_1.sequence, index_2=index_2.sequence[: len(index_1.sequence)]
            )
        elif index_1.type == IndexType.INDEX_2:
            return string_hamming_distance(
                index_1=index_1.sequence, index_2=index_2.sequence[-len(index_1.sequence) :]
            )
```

Here it's a bit confusing as I numbered the type constants instead of having something like I7_INDEX, might change this. 

But it will only compare the first bases with eachother if it is an i7 index (also called index 1):
```
ATGC
||||
ATGCTT
```

While the opposite is done if i5 indexes (index 2s) are compared to eachother:
```
  ATGC
  ||||
ATGCTT
```

If index 1 is longer than index 2 then of course the opposite is done.

So it should work as intended, but let me know if you've seen something that I've missed!

**Comment by diitaz93** [comment]
@karlnyr was the one who noticed this. The problem is that right now the sample sheet creation on cg is considering all indices like index2. So one of the methods should change

**Comment by Karl-Svard** [comment]
Why are we considering all indexes like that in cg?

**Comment by diitaz93** [comment]
Because we thought that as the reverse complement is not used for NovaSeqX, the indices should not be flipped either

**Comment by Karl-Svard** [comment]
But they aren't flipped with this logic 🤔

Let's say we have two reads with differing index lengths:
```
ATGTTTGC - XXXX - CGGTAAGT
ATGTTTGCAT - XXXX - CTTGATGGTA
```

Then the OverrideCycles settings `Y151;I8N2;N2I8;Y151` will be used on the smaller indexed sample, which to my understanding means that it essentially is interpreted as:
```
ATGTTTGCNN - XXXX - NNCGGTAAGT
ATGTTTGCAT - XXXX - CTTGATGGTA
```

That means that we get two types of comparisons depending on which index it is:
Index 1
```
ATGTTTGCNN
||||||||
ATGTTTGCAT
```

Index 2
```
NNCGGTAAGT
  x|x|xxxx
CTTGATGGTA
```

Maybe we should have meeting all together to discuss which way is the correct one

**Comment by diitaz93** [comment]
Fixed in cg on https://github.com/Clinical-Genomics/cg/pull/2454#issuecomment-1715550155
