### ISSUE TITLE
Compliance to Atlas document Validation and verifications and suggestion for improvment to templates

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cg_lims#541]
Hi LIMS team!

I'm doing Yearly revision of the [Validation and verification documentation, section LIMS](https://atlas.scilifelab.se/quality_assurance/validation/validation_and_verification/#validations-and-verifications-in-lims).

Can you go through the issue templates and make sure that they are compliant with the instructions in Atlas?
tex,

- add who can sign of on a verification
- add a verification label to the verification templates (so they can be sorted by label) and other labels as needed (tex New workflow) _This is not required but nice to have to be able ti identify the verifications_

Is a verification always a minor or is this decide from case to case? And if so, by whom?

**Comment by Karl-Svard** [comment]
The verification template in cg_lims looks good. But it would be nice if @idalindegaard could take an extra look as well. 

We have also set up so that labels are automatically added for verification issues.

Regarding the comment about 'minor', I'm not really sure what you mean. The current process is to document verifications as issues, not PRs, so there's no versioning being made.

**Comment by idalindegaard** [comment]
We discussed this and decided that we will update the Atlas documentation a bit, can you send me the link to your yearly review PR and I can make some changes there @AnnaLeinfelt?

**Comment by idalindegaard** [comment]
Here is a [PR](https://github.com/Clinical-Genomics/atlas/pull/3078) with an update of the verification routine that I think is more optimal for us. Could one of you review it? @AnnaLeinfelt @Karl-Svard
