### ISSUE TITLE
Update Queue samples for sequencing configuration in several LIMS workflows

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#546]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** 

Issue #545 describes a (quite unlikely) event that occurred when microbial samples had moved on to another workflow but the last step had not been completed, and when this non-completed step was aborted - the work started in a following step in the sequencing workflow was aborted, leading to unhappiness and extra work with relimsing. This was fixed for the microbial workflow in the mentioned issue, but this configuration is currently occurring in different variations in other workflows. A similar solution would be needed for those.

**Comment by AbiDalby** [comment]
For the TWIST v8 protocol, I have switched the EPP "Set Library Prep Date and Check Required and Queue samples for sequencing" to trigger automatically upon exit of the step. "Arnold Upload twist" now triggers automatically upon exit of Record Details. 
First tests looked good in stage, though samples with a red flag are still queued to seqwuencing even if "leave in QC protocol" is selected

**Comment by AbiDalby** [comment]
**Workflows: "TWIST v8", "SARS-CoV-2 v4", "WGS PCR free v6"**

The EPP in the final aggregation step of these workflows to queue samples for sequencing has been changed in production to activate automatically upon exit of step instead of at the end of "record details" view. This is to prevent accidental movement of samples before the step is completed.

EPPs:

__TWIST__: Set library prep date and check required and queue samples for sequencing
__SARS-CoV-2 v4__: Queue samples for sequencing (from QC step)
__WGS PCR free v6__: Set library prep date and queue samples for sequencing
